'use strict';
const HASH='c1939d444253d22a6eaefdeeccd7ada833180350a4341724dc8095fe760ac7e7';
const signs=[['aries','♈','fire'],['taurus','♉','earth'],['gemini','♊','air'],['cancer','♋','water'],['leo','♌','fire'],['virgo','♍','earth'],['libra','♎','air'],['scorpio','♏','water'],['sagittarius','♐','fire'],['capricorn','♑','earth'],['aquarius','♒','air'],['pisces','♓','water']];
const focuses=['self','love','work'];
const state={lang:'en',sign:null,focus:null,result:null,ratings:{clarity:0,relevance:0,trust:0,design:0}};
const C={
en:{
experienceNav:'Experience',feedbackNav:'Feedback',privacyNav:'Privacy',heroEyebrow:'Invite-only · No account · No payment',heroTitle:'Astrology made clearer, calmer and easier to explore.',heroText:'Test a short reflective experience built around one zodiac sign and one life focus. This evaluates the product experience—not a complete birth chart.',p1:'No birth data',p2:'No cookies or analytics',p3:'No posting required',start:'Start the 5-minute test',statusTitle:'Prototype status:',status:"Automated sample copy for product testing. It is not Sol Vartan's personal interpretation, not a complete birth chart and not a launched paid service.",guided:'Guided prototype',build:'Build a cosmic reflection',local:'Runs locally in your browser',signTitle:'Choose a zodiac sign',signHelp:'Use a sign you know well. No birth date is requested.',focusTitle:'Choose a focus',focusHelp:'What should the reflection help explore?',generate:'Generate reflection',prompt:'Choose one option in each step.',ready:'Ready to generate.',generated:'Prototype-generated sample',yourReflection:'Your reflection',reset:'Try another combination',usefulLabel:'What may be useful',watchLabel:'What to watch',questionLabel:'A useful question',actionLabel:'One grounded action',disclaimer:'For reflection and entertainment. Not medical, legal, financial or professional advice. No outcome is guaranteed.',feedbackEyebrow:'Independent feedback',feedbackTitle:'Tell us what worked—and what failed.',nothingSent:'Nothing is submitted',feedbackText:'Rate the experience and add concrete corrections. The page creates text you can copy into your reply.',clarity:'Clarity',relevance:'Relevance',trust:'Trust',design:'Visual design',notesLabel:'Three concrete corrections or observations',notesPlaceholder:'What would you change first?',prepare:'Prepare feedback',copy:'Copy feedback',thanks:'Thank you for being direct',criticism:'A useful criticism is worth more than a polite compliment.',reply:'Reply through the original invitation channel. No public post is expected.',copied:'Feedback copied. Paste it into your reply.',copyFail:'Copy failed. Select the text and copy it manually.',signNames:{aries:'Aries',taurus:'Taurus',gemini:'Gemini',cancer:'Cancer',leo:'Leo',virgo:'Virgo',libra:'Libra',scorpio:'Scorpio',sagittarius:'Sagittarius',capricorn:'Capricorn',aquarius:'Aquarius',pisces:'Pisces'},focusNames:{self:'Self & identity',love:'Relationships',work:'Direction & work'},focusHelp:{self:'Patterns, values and self-expression',love:'Connection, boundaries and communication',work:'Priorities, decisions and next steps'},
elements:{fire:['Momentum becomes useful when enthusiasm is attached to one specific choice.','Speed can replace listening and turn confidence into avoidable friction.','What deserves your courage now, and what is only asking for your impatience?','Complete one visible action within the next twenty-four hours.'],earth:['Stability becomes a strength when it supports movement rather than protecting an expired routine.','The search for certainty can delay a decision until the opportunity has already changed.','Which fact is truly missing, and which reassurance are you waiting to feel?','Put the smallest reversible next step on your calendar.'],air:['A clearer perspective appears when you stop collecting options and choose one idea to test.','Analysis can multiply possibilities faster than it creates clarity.','Which conversation would become simpler if you said what you actually need?','Write one sentence that names your priority without defending it.'],water:['Sensitivity becomes practical intelligence when it is translated into a boundary, request or decision.','Absorbing every atmosphere can make your own preference difficult to hear.','Which feeling belongs to you, and which may have been borrowed from the room?','Create ten quiet minutes before answering the next emotional request.']},
foci:{self:['For identity, this favors honest self-definition over performing the version others expect.','The risk is using a label to avoid noticing how you are already changing.','What part of your current identity is alive, and what part is only familiar?','Remove one sentence from the story you keep repeating about yourself.'],love:['For relationships, this points toward clearer reciprocity instead of guessing the other person’s intention.','The risk is confusing intensity, harmony or availability with mutual commitment.','Where would one honest boundary create more trust than another adaptation?','Make one precise request and allow the other person to answer freely.'],work:['For direction and work, this favors a testable priority over a perfect master plan.','The risk is treating every attractive option as equally urgent.','If one decision could move this week, which would reduce the most uncertainty?','Define a seven-day experiment with one measurable outcome.']}
},
es:{
experienceNav:'Experiencia',feedbackNav:'Feedback',privacyNav:'Privacidad',heroEyebrow:'Solo por invitación · Sin cuenta · Sin pago',heroTitle:'Astrología más clara, serena y fácil de explorar.',heroText:'Prueba una experiencia breve basada en un signo y un enfoque vital. Evalúa el producto, no una carta natal completa.',p1:'Sin datos de nacimiento',p2:'Sin cookies ni analítica',p3:'Sin obligación de publicar',start:'Empezar la prueba de 5 minutos',statusTitle:'Estado del prototipo:',status:'Texto automático para probar el producto. No es una interpretación personal de Sol Vartan, no es una carta natal completa y no es un servicio de pago lanzado.',guided:'Prototipo guiado',build:'Construye una reflexión cósmica',local:'Funciona localmente en tu navegador',signTitle:'Elige un signo zodiacal',signHelp:'Usa un signo que conozcas bien. No pedimos fecha de nacimiento.',focusTitle:'Elige un enfoque',focusHelp:'¿Qué debería ayudarte a explorar?',generate:'Generar reflexión',prompt:'Elige una opción en cada paso.',ready:'Listo para generar.',generated:'Muestra generada por el prototipo',yourReflection:'Tu reflexión',reset:'Probar otra combinación',usefulLabel:'Lo que puede ser útil',watchLabel:'Qué vigilar',questionLabel:'Una pregunta útil',actionLabel:'Una acción concreta',disclaimer:'Para reflexión y entretenimiento. No es asesoramiento médico, legal, financiero o profesional. No garantiza resultados.',feedbackEyebrow:'Feedback independiente',feedbackTitle:'Dinos qué funcionó y qué falló.',nothingSent:'No se envía nada',feedbackText:'Puntúa la experiencia y añade correcciones. La página crea texto para copiar en tu respuesta.',clarity:'Claridad',relevance:'Relevancia',trust:'Confianza',design:'Diseño visual',notesLabel:'Tres correcciones u observaciones concretas',notesPlaceholder:'¿Qué cambiarías primero?',prepare:'Preparar feedback',copy:'Copiar feedback',thanks:'Gracias por ser directo/a',criticism:'Una crítica útil vale más que un cumplido educado.',reply:'Responde por el canal original. No esperamos una publicación pública.',copied:'Feedback copiado. Pégalo en tu respuesta.',copyFail:'No se pudo copiar. Selecciona el texto y cópialo.',signNames:{aries:'Aries',taurus:'Tauro',gemini:'Géminis',cancer:'Cáncer',leo:'Leo',virgo:'Virgo',libra:'Libra',scorpio:'Escorpio',sagittarius:'Sagitario',capricorn:'Capricornio',aquarius:'Acuario',pisces:'Piscis'},focusNames:{self:'Identidad',love:'Relaciones',work:'Dirección y trabajo'},focusHelp:{self:'Patrones, valores y expresión personal',love:'Vínculos, límites y comunicación',work:'Prioridades, decisiones y próximos pasos'},
elements:{fire:['El impulso se vuelve útil cuando el entusiasmo se conecta con una decisión concreta.','La velocidad puede sustituir a la escucha y convertir la confianza en fricción evitable.','¿Qué merece ahora tu valentía y qué solo está pidiendo tu impaciencia?','Completa una acción visible durante las próximas veinticuatro horas.'],earth:['La estabilidad es una fuerza cuando sostiene el movimiento y no protege una rutina caducada.','La búsqueda de certeza puede retrasar una decisión hasta que la oportunidad ya cambió.','¿Qué dato falta de verdad y qué tranquilidad estás esperando sentir?','Pon en tu agenda el siguiente paso reversible más pequeño.'],air:['Aparece claridad cuando dejas de coleccionar opciones y eliges una idea para probar.','El análisis puede multiplicar posibilidades más rápido de lo que produce claridad.','¿Qué conversación sería más simple si dijeras lo que realmente necesitas?','Escribe una frase que nombre tu prioridad sin defenderla.'],water:['La sensibilidad se convierte en inteligencia práctica cuando se traduce en un límite, una petición o una decisión.','Absorber cada ambiente puede dificultar escuchar tu propia preferencia.','¿Qué emoción te pertenece y cuál podría venir del entorno?','Crea diez minutos de silencio antes de responder a la próxima petición emocional.']},
foci:{self:['Para la identidad, favorece una definición honesta frente a representar la versión que otros esperan.','El riesgo es usar una etiqueta para no reconocer cómo ya estás cambiando.','¿Qué parte de tu identidad actual está viva y cuál solo resulta familiar?','Elimina una frase de la historia que sigues repitiendo sobre ti.'],love:['Para las relaciones, invita a una reciprocidad más clara en vez de adivinar la intención de la otra persona.','El riesgo es confundir intensidad, armonía o disponibilidad con compromiso mutuo.','¿Dónde un límite honesto generaría más confianza que otra adaptación?','Haz una petición precisa y deja que la otra persona responda libremente.'],work:['Para la dirección y el trabajo, favorece una prioridad comprobable frente a un plan perfecto.','El riesgo es tratar cada opción atractiva como igualmente urgente.','Si una decisión pudiera avanzar esta semana, ¿cuál reduciría más incertidumbre?','Define un experimento de siete días con un resultado medible.']}
}};
function t(k){return C[state.lang][k]}
async function sha(v){const b=new TextEncoder().encode(v.trim().toUpperCase()),d=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function unlock(){const e=document.getElementById('gate-error');e.textContent='';if(await sha(document.getElementById('code').value)!==HASH){e.textContent='Invalid access code.';return}document.getElementById('gate').hidden=true;document.getElementById('app').hidden=false;render()}
document.getElementById('unlock').onclick=unlock;document.getElementById('code').onkeydown=e=>{if(e.key==='Enter')unlock()};
function translate(){document.documentElement.lang=state.lang;document.querySelectorAll('[data-t]').forEach(n=>{if(typeof t(n.dataset.t)==='string')n.textContent=t(n.dataset.t)});document.querySelectorAll('[data-placeholder]').forEach(n=>n.placeholder=t(n.dataset.placeholder))}
function choice(id,label,help,group,symbol=''){const b=document.createElement('button');b.type='button';b.className='choice'+(state[group]===id?' selected':'');b.setAttribute('role','radio');b.setAttribute('aria-checked',state[group]===id?'true':'false');b.innerHTML=`<strong>${symbol?`<span class="zodiac">${symbol}</span>`:''}${label}</strong><small>${help}</small>`;b.onclick=()=>{state[group]=id;options();ready()};return b}
function options(){const s=document.getElementById('signs');s.replaceChildren();signs.forEach(x=>s.appendChild(choice(x[0],t('signNames')[x[0]],x[2],'sign',x[1])));const f=document.getElementById('focuses');f.replaceChildren();focuses.forEach(x=>f.appendChild(choice(x,t('focusNames')[x],t('focusHelp')[x],'focus')))}
function ready(){const ok=state.sign&&state.focus;document.getElementById('generate').disabled=!ok;document.getElementById('ready').textContent=ok?t('ready'):t('prompt')}
function render(){translate();options();ready();if(state.result)show()}
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;document.querySelectorAll('.lang').forEach(x=>x.classList.toggle('active',x===b));render()});
document.getElementById('generate').onclick=()=>{const s=signs.find(x=>x[0]===state.sign),e=C[state.lang].elements[s[2]],f=C[state.lang].foci[state.focus];state.result={symbol:s[1],texts:e.map((x,i)=>x+' '+f[i])};show();document.getElementById('result').hidden=false;document.getElementById('result').scrollIntoView({behavior:'smooth'})};
function show(){const r=state.result;if(!r)return;document.getElementById('symbol').textContent=r.symbol;['useful','watch','question','action'].forEach((id,i)=>document.getElementById(id).textContent=r.texts[i]);const tags=document.getElementById('tags');tags.replaceChildren();[r.symbol+' '+t('signNames')[state.sign],t('focusNames')[state.focus]].forEach(x=>{const s=document.createElement('span');s.textContent=x;tags.appendChild(s)})}
document.getElementById('reset').onclick=()=>{state.sign=null;state.focus=null;state.result=null;document.getElementById('result').hidden=true;options();ready();document.getElementById('experience').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('.rating').forEach(c=>{const k=c.dataset.rating;for(let i=1;i<=5;i++){const b=document.createElement('button');b.type='button';b.textContent=i;b.onclick=()=>{state.ratings[k]=i;c.querySelectorAll('button').forEach((x,j)=>x.classList.toggle('selected',j<i))};c.appendChild(b)}});
document.getElementById('prepare').onclick=()=>{const l=C[state.lang],combo=state.result?`${l.signNames[state.sign]} / ${l.focusNames[state.focus]}`:'No reflection generated',ratings=Object.entries(state.ratings).map(([k,v])=>`${k}: ${v||'not rated'}/5`).join(' · ');document.getElementById('output').value=`WOW ASTRO PRIVATE BETA — TESTER FEEDBACK\n\nTested: ${combo}\nRatings: ${ratings}\n\nCorrections / observations:\n${document.getElementById('notes').value.trim()||'—'}\n\nNo public post was required and no positive review was requested.`;document.getElementById('copy').disabled=false};
document.getElementById('copy').onclick=async()=>{const o=document.getElementById('output');try{await navigator.clipboard.writeText(o.value);document.getElementById('copy-status').textContent=t('copied')}catch{o.select();document.getElementById('copy-status').textContent=t('copyFail')}};
